### ISSUE TITLE
Background theme not appearing

### ISSUE THREAD

**Issue by Naranzhia** [Jiiks/BetterDiscordApp#703] opened 2018-02-09 15:21 UTC
It's been 1-2 weeks since I've encountered this issue, it makes me feel uncomfortable because I can't see my waifu on the back....
Basically, I have the correct script and stuff, it's just that the background isn't appearing.

**Comment by DevilsLynAvenged** [comment] 2018-02-09 15:36
```CSS
/* fix not having a background image anymore */
.layers-20RVFW, .layer-kosS71, .container-2OU7Cz, .typing-3eiiL_ {
  background: transparent !important;
}
/* optionally adjust background brightness (0: original image, 1: black) */
.layers-20RVFW {
  background: rgba(0,0,0, 0.3) !important;
}``` did you add this already?

**Comment by RoryTheReaper** [comment] 2018-02-10 00:30
How do you use that code to fix the issue? (I have no experience with coding, I'm just here for help.)

**Comment by OutDark** [comment] 2018-02-10 05:26
Duplicate of #693

**Comment by Dahipppo1555** [comment] 2018-02-10 10:35
huh fixed try it
put this in custom CSS at discord settings
`/* fix not having a background image anymore */
.layers-20RVFW, .layer-kosS71, .container-2OU7Cz, .typing-3eiiL_ {
  background: transparent !important;
}
/* optionally adjust background brightness (0: original image, 1: black) */
.layers-20RVFW {
  background: rgba(0,0,0, 0.3) !important;
}`
and use themefix.theme.css from this rar and put it in %appdata%/betterdiscord/themes and enable it in themes in discord 
RAR [https://drive.google.com/file/d/1v9FZ7LqSskHSEAZTMdXsz7gUjCuI0hQT/view?usp=sharing](url)
simple and ez :)

**Closed** 2018-07-21 21:48 UTC
